export const EXCEPTION = {
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXISTS: 'User already exists',
  INVALID_PASSWORD: 'Invalid password',
  DEVELOPER_NOT_FOUND: 'Developer not found',
  SALE_NOT_FOUND: 'Sale not found',
  WORKACCOUNT_NOT_FOUND: 'WorkAccount not found',
  CUSTOMER_NOT_FOUND: 'Customer not found',
  REPORT_NOT_FOUND: 'Report not found',
  DEVELOPERS_ON_CUSTOMERS_NOT_FOUND: 'Assign not found',
  INCOME_NOT_FOUND: 'Income not found',
  EMPLOYEE_NOT_FOUND: 'Employee not found',
  PROJECT_MANAGER_NOT_FOUND: 'Project manager not found',
  PROJECT_NOT_FOUND: 'Project not found',
  TEAM_NOT_FOUND: 'Team not found',
};
